---
- name: Check the user home directory exists
  stat:
    path: "{{ user.home_dir.rstrip('/') }}"
  register: user_home_dir
  tags:
    - configuration
    - user
    - package
    - package-check-user-home-directory

- name: Create a local bin directory
  become_user: "{{ user.name }}"
  file:
    path: "{{ user.home_dir.rstrip('/') }}/bin"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0755
  when: user_home_dir.stat.exists
  tags:
    - configuration
    - user
    - package
    - package-create-bin-directory

- name: Check the user bin directory exists
  stat:
    path: "{{ user.home_dir.rstrip('/') }}/bin"
  register: user_bin_dir
  tags:
    - configuration
    - user
    - package
    - package-check-user-bin-directory
    - package-install-pyenv
    - package-install-rbenv
    - package-install-ruby-build
    - package-download-opam
    - package-link-opam
    - package-initialize-opam
    - package-copy-zsh-settings

- name: Install pyenv dependency packages for Debian
  package:
    name:
      - gcc
      - make
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - curl
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libxml2-dev
      - libxmlsec1-dev
      - libffi-dev
      - liblzma-dev
    state: present
  when: ansible_facts['os_family'] == 'Debian'
  tags:
    - configuration
    - user
    - package
    - package-install-pyenv-dependencies

- name: Install pyenv dependency packages for CentOS
  package:
    name:
      - gcc
      - make
      - zlib-devel
      - bzip2
      - bzip2-devel
      - readline
      - readline-devel
      - sqlite
      - qslite-devel
      - openssl-devel
      - tk-devel
      - libffi-devel
      - xz-devel
    state: present
  when: ansible_facts['os_family'] == 'RedHat'
  tags:
    - configuration
    - user
    - package
    - package-install-pyenv-dependencies

- name: Install pyenv
  become_user: "{{ user.name }}"
  git:
    repo: "{{ pyenv_repo }}"
    dest: "{{ user.home_dir.rstrip('/') }}/.pyenv"
    version: "{{ pyenv_version }}"
  when: user_home_dir.stat.exists
  tags:
    - configuration
    - user
    - package
    - package-install-pyenv

- name: Install rbenv
  become_user: "{{ user.name }}"
  git:
    repo: "{{ rbenv_repo }}"
    dest: "{{ user.home_dir.rstrip('/') }}/.rbenv"
    version: "{{ rbenv_version }}"
  when: user_home_dir.stat.exists
  tags:
    - configuration
    - user
    - package
    - package-install-rbenv

- name: Install ruby-build
  become_user: "{{ user.name }}"
  git:
    repo: "{{ ruby_build_repo }}"
    dest: "{{ user.home_dir.rstrip('/') }}/.rbenv/plugins/ruby-build"
    version: "{{ ruby_build_version }}"
  when: user_home_dir.stat.exists
  tags:
    - configuration
    - user
    - package
    - package-install-ruby-build

# Reference: https://github.com/andrewrothstein/ansible-opam
- name: Install opam dependency packages for Debian
  package:
    name:
      - bubblewrap
      - zip
      - unzip
      - rsync
      - mercurial
      - darcs
    state: present
  when: ansible_facts['os_family'] == 'Debian'
  tags:
    - configuration
    - user
    - package
    - package-install-opam-dependencies

- name: Install opam dependency packages for CentOS
  package:
    name:
      - bubblewrap
      - zip
      - unzip
      - rsync
      - mercurial
    state: present
  when: ansible_facts['os_family'] == 'RedHat'
  tags:
    - configuration
    - user
    - package
    - package-install-opam-dependencies

- name: Download opam
  become_user: "{{ user.name }}"
  get_url:
    url: "{{ opam_mirror }}/{{ opam_version }}/{{ opam_bin }}"
    dest: "{{ user.home_dir.rstrip('/') }}/bin"
    mode: 0755
  when: user_bin_dir.stat.exists
  tags:
    - configuration
    - user
    - package
    - package-download-opam

- name: Link the opam target
  become_user: "{{ user.name }}"
  file:
    src: "{{ user.home_dir.rstrip('/') }}/bin/{{ opam_bin }}"
    dest: "{{ user.home_dir.rstrip('/') }}/bin/opam"
    state: link
  when: user_bin_dir.stat.exists
  tags:
    - configuration
    - user
    - package
    - package-link-opam

- name: Initialize opam
  become_user: "{{ user.name }}"
  command: "{{ user.home_dir.rstrip('/') }}/bin/opam init -y --comp {{ opam_ocaml_version }}"
  args:
    creates: "{{ user.home_dir.rstrip('/') }}/.opam"
  register: opam_init_result
  ignore_errors: yes
  changed_when: false
  when: opam_init and user_bin_dir.stat.exists
  tags:
    - configuration
    - user
    - package
    - package-initialize-opam

- name: Install zsh
  package:
    name:
      - zsh
    state: present
  tags:
    - configuration
    - user
    - package
    - package-install-zsh

- name: Set git path
  command: which git
  register: git_path
  changed_when: git_path.stdout == ''
  tags:
    - configuration
    - user
    - package
    - package-set-git-path

- name: Download zsh settings
  git:
    repo: "{{ zsh_settings_repo }}"
    dest: "{{ zsh_settings_dest }}"
    version: "{{ zsh_settings_version }}"
  when:
    - git_path is defined and (git_path.stdout | default('') | length > 0)
  tags:
    - configuration
    - user
    - package
    - package-download-zsh-settings

- name: Check the zsh settings directory exists
  stat:
    path: "{{ zsh_settings_dest }}"
  register: zsh_settings_dir
  tags:
    - configuration
    - user
    - package
    - package-check-zsh-settings-directory

- name: Set zsh path
  command: which zsh
  register: zsh_path
  changed_when: zsh_path.stdout == ''
  tags:
    - configuration
    - user
    - package
    - package-set-zsh-path

- name: Copy zsh settings
  copy:
    remote_src: yes
    src: "/tmp/zsh_settings/{{ item }}"
    dest: "{{ user.home_dir.rstrip('/') }}/{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0644
  with_items:
    - .zshrc
    - .zshenv
  when:
    - user_home_dir.stat.exists
    - zsh_settings_dir.stat.exists
  tags:
    - configuration
    - user
    - package
    - package-copy-zsh-settings

- name: Change the login shell
  command: "chsh -s {{ zsh_path.stdout }} {{ user.name }}"
  when:
    - zsh_path is defined and (zsh_path.stdout | default('') | length > 0)
  changed_when: false
  tags:
    - configuration
    - user
    - package
    - package-change-login-shell
