- name: Create groups
  group:
    name: "{{ user.name }}"
    state: present
  tags:
    - usersetting

- name: Create users
  user:
    name: "{{ user.name }}"
    group: "{{ user.name }}"
    groups: "{{ user.groups }}"
    append: yes
    password: "{{ user.password | password_hash('sha512') }}"
  tags:
    - usersetting

- name: Create a local bin directory
  file:
    path: "/home/{{ user.name }}/bin"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0755
  tags:
    - usersetting
