---
- name: Create groups
  group:
    name: "{{ user.name }}"
    state: present
  when: not user.name == 'root'
  tags:
    - configuration
    - user
    - user-create-groups

- name: Create users
  user:
    name: "{{ user.name }}"
    group: "{{ user.name }}"
    groups: "{{ user.groups }}"
    append: yes
    password: "{{ user.password | password_hash('sha512') }}"
  when: not user.name == 'root'
  tags:
    - configuration
    - user
    - user-create-user

- name: Create a local bin directory
  file:
    path: "{{ user.home_dir.rstrip('/') }}/bin"
    state: directory
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0755
  tags:
    - configuration
    - user
    - user-create-bin-directory
